// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"github.com/tphoney/musicscan/internal/router"
	"github.com/tphoney/musicscan/internal/server"
	"github.com/tphoney/musicscan/internal/store/database"
	"github.com/tphoney/musicscan/internal/store/memory"
	"github.com/tphoney/musicscan/types"
)

// Injectors from wire.go:

func initServer(config *types.Config) (*server.Server, error) {
	db, err := database.ProvideDatabase(config)
	if err != nil {
		return nil, err
	}
	albumStore := database.ProvideAlbumStore(db)
	artistStore := database.ProvideArtistStore(db)
	memberStore := database.ProvideMemberStore(db)
	projectStore := database.ProvideProjectStore(db)
	userStore := database.ProvideUserStore(db)
	systemStore := memory.New(config)
	handler := router.New(albumStore, artistStore, memberStore, projectStore, userStore, systemStore)
	serverServer := server.ProvideServer(config, handler)
	return serverServer, nil
}
